name: app-workflow

on:
  push:
    branches: [ master ]

jobs:
  test-app:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        cd app
        npm install
        npm test a

  deploy-app:
    needs: test-app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lauches deploy hook in Netlify
      run: curl -X POST -d {} https://api.netlify.com/build_hooks/5ef0d0d7f675d97f88ecb5f8