name: deploy

on:
  push:
    branches: [ master ]

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Heroku Container registry
        run: docker login --username=_ --password=${{ secrets.HEROKU_API_KEY }} registry.heroku.com
      - name: Build and push
        run: |
          docker build -t werow .
          docker tag werow:latest registry.heroku.com/werow-app/web
      - name: Release
        run: docker run --rm -e HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} wingrunr21/alpine-heroku-cli container:release web --app werow-app